<?php

global $_LANGMAIL;
$_LANGMAIL = array();
$_LANGMAIL['New credit slip regarding your order'] = 'Новая информация по Вашему заказу';
$_LANGMAIL['An answer to your message is available #ct%1$s #tc%2$s'] = 'Ответ на Ваше сообщение доступен #ct%1$s #tc%2$s ';
$_LANGMAIL['Congratulations!'] = 'Поздравляем!';
$_LANGMAIL['Stock coverage'] = 'Покрытие запасов';
$_LANGMAIL['Message from '] = 'Сообщение от ';
$_LANGMAIL[' $subject'] = ' $subject';
$_LANGMAIL['Message from a customer'] = 'Комментарий к заказу';
$_LANGMAIL['New voucher regarding your order %s'] = 'Новый купон для Вашего заказа %s';
$_LANGMAIL['Your password'] = 'Ваш пароль';
$_LANGMAIL['Message from %1$s %2$s'] = 'Сообщение от %1$s %2$s ';
$_LANGMAIL['Fwd: Customer message'] = 'Сообщение клиента';
$_LANGMAIL['Your cart and your discount'] = 'Ваша корзина и ваша скидка';
$_LANGMAIL['Password query confirmation'] = 'Подтверждение смены пароля';
$_LANGMAIL['Product out of stock'] = 'Товар отсуствует на складе';
$_LANGMAIL['Referral Program'] = 'Реферральная программа';
$_LANGMAIL['New voucher regarding your order'] = 'Новый купон за ваш заказ';
$_LANGMAIL['Virtual product to download'] = 'Ссылки на загрузку товара';
$_LANGMAIL['Thanks for your order'] = 'Спасибо за Ваш заказ!';
$_LANGMAIL['[Log'] = '[Лог';
$_LANGMAIL['You are one of our best customers'] = 'Благодарим Вас за то, что Вы являетесь одним из наших лучших клиентов';
$_LANGMAIL['Email verification'] = 'Email верификация';
$_LANGMAIL['You are one of our best customers!'] = 'Вы являетесь одним из наших лучших клиентов!';
$_LANGMAIL['Error reporting from your PayPal module'] = 'Ошибка от Вашего модуля PayPal';
$_LANGMAIL['Package in transit'] = 'Заказ в пути';
$_LANGMAIL['Product available'] = 'Товар доступен';
$_LANGMAIL['A friend sent you a link to'] = 'Друг отправил вам ссылку';
$_LANGMAIL['Welcome!'] = 'Добро пожаловать!';
$_LANGMAIL['Message from contact form'] = 'Сообщение контактной формы';
$_LANGMAIL['Your order has been changed'] = 'Ваш заказ был изменен';
$_LANGMAIL['Thank you for your order.'] = 'Спасибо за Ваш заказ.';
$_LANGMAIL['Newsletter voucher'] = 'Купон за подписку';
$_LANGMAIL['Your guest account has been transformed to customer account'] = 'Ваш гостевой аккаунт преобразован в аккаунт покупателя';
$_LANGMAIL['New message regarding your order'] = 'Новый комментарий к заказу';
$_LANGMAIL['Happy birthday!'] = 'С Днем Рождения!';
$_LANGMAIL['An answer to your message is available'] = 'Доступен ответ на ваше сообщение';
$_LANGMAIL['We miss you!'] = 'Мы скучаем по Вам!';
$_LANGMAIL['We miss you'] = 'Мы соскучились за Вами';
$_LANGMAIL['Your new password'] = 'Ваш новый пароль';
$_LANGMAIL['Process the payment of your order'] = 'Произвести оплату вашего заказа';
$_LANGMAIL['Log: You have a new alert from your shop'] = 'Журнал: есть новое предупреждение для вашего магазина';
$_LANGMAIL['Your order return state has changed'] = 'Статус возврата Вашего заказа был изменен';
$_LANGMAIL['Your message has been correctly sent'] = 'Ваше сообщение отправлено';
$_LANGMAIL['Your wishlist\\\'s link'] = 'Ссылка на Ваш список желаний';
$_LANGMAIL['Newsletter confirmation'] = 'Подтверждение подписки на новости';
$_LANGMAIL['Order confirmation'] = 'Подтверждение заказа';

?>